name: Test pytest-regsmart (without any ranking mode, selection via file)

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run tests (pytest-regsmart - RTS Only and per file)
        run: uv run pytest -v --regsmart --diff-level=file --no-rank
