name: Test pytest-regsmart

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git fetch --depth=1 origin main:refs/remotes/origin/main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run tests (pytest normal)
        run: uv run pytest -v

      - name: Run tests (pytest-regsmart)
        run: uv run pytest --regsmart -v
